
let firstName = prompt("Enter your First Name:");
let lastName = prompt("Enter your Last Name:");
let email = prompt("Enter your Email:");
let phoneNumber = prompt("Enter your Phone Number:");
let password = prompt("Enter your Password:");


alert("First Name: " + firstName);
alert("Last Name: " + lastName);
alert("Email: " + email);
alert("Phone Number: " + phoneNumber);
alert("Password: " + password);






alert("You're learning JavaScript!");





alert("Hello! Welcome to JavaScript.");

